### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by Einkornwolf** [CapOliveiraBr/DBM-Firebase#1]
I followed all the instructions and then proceeded to test the Mod. When I type my testing command which should write something into firebase, nothing happens... no console error ( only once ) no write in firebase

**Comment by cappp** [comment]
I know, i will fix in the next release, just wait.

**Comment by cappp** [comment]
Fixed! See: https://github.com/cappp/dbm-firebase/releases/tag/1.1.3
