### ISSUE TITLE
Store Firebase Member Data don't store values ​​= 0

### ISSUE THREAD

**Issue by LexPlayGames** [CapOliveiraBr/DBM-Firebase#11]
The Store Firebase Member Data action doesn't store values ​​equal to 0. If the Data value is = 0, it simply does not store the value and doesn't advance to the next action. Could you have a look please? I noticed this only on Store Firebase Member Data. In other actions I didn't notice this problem.

**Comment by cappp** [comment]
Only English, please.

**Comment by cappp** [comment]
Anyway, i'll check.

**Comment by LexPlayGames** [comment]
tks cappp and sorry for the portuguese. lol

**Comment by cappp** [comment]
Fixed, see: https://github.com/cappp/dbm-firebase/releases/tag/1.1.8.

**Comment by cappp** [comment]
I gonna close this issue now, open a new issue if you find another bug posteriorly. 👍

**Comment by LexPlayGames** [comment]
thank you vrey much
