### ISSUE TITLE
Can't Store Multiple Data Values

### ISSUE THREAD

**Issue by Echo-Script** [CapOliveiraBr/DBM-Firebase#8]
Hey, I recently had an issue trying to send / receive data using this mod, I managed to fix that, however, everytime you store more than one value, one will show up as **undefined**.

**Comment by cappp** [comment]
I have tested that and all have ocurred normally.

![image](https://user-images.githubusercontent.com/48036034/87826027-928deb00-c84e-11ea-9c35-e5da07de3cc5.png)
![image](https://user-images.githubusercontent.com/48036034/87826075-a33e6100-c84e-11ea-890e-4c38d9174826.png)

**Comment by Echo-Script** [comment]
![image](https://user-images.githubusercontent.com/50340593/87826145-42c01b80-c870-11ea-9315-86b684be017a.png)

![image](https://user-images.githubusercontent.com/50340593/87826173-4fdd0a80-c870-11ea-9e6c-4727825cf189.png)

**Comment by Echo-Script** [comment]
![image](https://user-images.githubusercontent.com/50340593/87826220-671bf800-c870-11ea-9b7a-68236a9da3ab.png)

**Comment by cappp** [comment]
Send me a print inside of the action that contains the points.

![image](https://user-images.githubusercontent.com/48036034/87826566-848c9a00-c84f-11ea-93e5-c7931dfd86ab.png)

**Comment by Echo-Script** [comment]
![image](https://user-images.githubusercontent.com/50340593/87826941-b0b91280-c871-11ea-94c3-fc475280fff2.png)

**Comment by Echo-Script** [comment]
Hold on, it seems to only give me undefined when I use an embed, weird, it works in raw text - its not your mod - sorry if I wasted your time!

**Comment by cappp** [comment]
Weird. Well, if soon you find some bug, not forget to open an issue!
